name: Upload Package

on:
  pull_request:
  push:
    branches: [ master, main, develop ]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.6
        with:
          versionSpec: '5.x'
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.6
        with:
          useConfigFile: true
          showConfig: true
          configFilePath: ./gitversion.yml
      - name: Display SemVer
        run: |
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: DamianReeves/write-file-action@master
        with:
          path: src/.version
          write-mode: overwrite
          contents: ${{ needs.version.outputs.version }}
      - uses: BenMMcLean/pkl-upload-package/v1.1.0
        with:
          input-directory: test